# Used to optimize the `generate_release_notes` required in workflows/release.yml
changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Breaking Changes ⚠️
      labels:
        - breaking-change
    - title: New Features ✨
      labels:
        - enhancement
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
        - fix
    - title: Documentation 📚
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"