org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
android.dependency.useConstraints=false
#android.r8.strictFullModeForKeepRules=false
android.builtInKotlin=false
# NOTE: set android.newDsl=false!
# Because if it's true, you must set builtInKotlin = true, while then it cause 3rd plugin issues
android.newDsl=false
org.gradle.version-catalog.watch=true
org.gradle.unsafe.watch-fs=true